"""2

Revision ID: 757f0953e1ba
Revises: afade2012d1c
Create Date: 2023-05-24 06:42:26.930223

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "757f0953e1ba"
down_revision = "afade2012d1c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bank_statement", sa.Column("contract_number", sa.String(), nullable=False)
    )
    op.add_column(
        "bank_statement", sa.Column("account_number", sa.String(), nullable=False)
    )
    op.add_column("bank_statement", sa.Column("card", sa.String(), nullable=False))
    op.add_column(
        "bank_statement", sa.Column("branch_of_the_bank", sa.String(), nullable=False)
    )
    op.add_column(
        "bank_statement", sa.Column("main_currency", sa.String(), nullable=False)
    )
    op.add_column("bank_statement", sa.Column("period", sa.String(), nullable=False))
    op.add_column(
        "bank_statement", sa.Column("client_name", sa.String(), nullable=False)
    )
    op.add_column(
        "bank_statement", sa.Column("transaction", sa.String(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bank_statement", "transaction")
    op.drop_column("bank_statement", "client_name")
    op.drop_column("bank_statement", "period")
    op.drop_column("bank_statement", "main_currency")
    op.drop_column("bank_statement", "branch_of_the_bank")
    op.drop_column("bank_statement", "card")
    op.drop_column("bank_statement", "account_number")
    op.drop_column("bank_statement", "contract_number")
    # ### end Alembic commands ###
