"""create_bank_model

Revision ID: afade2012d1c
Revises: 6570cbbcc6fe
Create Date: 2023-05-24 02:12:45.829246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "afade2012d1c"
down_revision = "6570cbbcc6fe"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bank_statement", sa.Column("user_id", sa.UUID(as_uuid=False), nullable=False)
    )
    op.create_foreign_key(
        None, "bank_statement", "user_model", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "bank_statement", type_="foreignkey")
    op.drop_column("bank_statement", "user_id")
    # ### end Alembic commands ###
