"""create_bank_statement_model

Revision ID: 6570cbbcc6fe
Revises: 07c71f4389b6
Create Date: 2023-05-24 01:21:31.344095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6570cbbcc6fe"
down_revision = "07c71f4389b6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bank_statement",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("base64_bank_statement", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("base64_bank_statement"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bank_statement")
    # ### end Alembic commands ###
