"""created_models

Revision ID: 347b67015248
Revises: 757f0953e1ba
Create Date: 2023-05-24 06:55:22.768263

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "347b67015248"
down_revision = "757f0953e1ba"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "bank_statement",
        "contract_number",
        existing_type=sa.VARCHAR(),
        type_=sa.Text(),
        nullable=True,
    )
    op.alter_column(
        "bank_statement",
        "account_number",
        existing_type=sa.VARCHAR(),
        type_=sa.Text(),
        nullable=True,
    )
    op.alter_column(
        "bank_statement",
        "card",
        existing_type=sa.VARCHAR(),
        type_=sa.Text(),
        nullable=True,
    )
    op.alter_column(
        "bank_statement",
        "branch_of_the_bank",
        existing_type=sa.VARCHAR(),
        type_=sa.Text(),
        nullable=True,
    )
    op.alter_column(
        "bank_statement",
        "main_currency",
        existing_type=sa.VARCHAR(),
        type_=sa.Text(),
        nullable=True,
    )
    op.alter_column(
        "bank_statement",
        "period",
        existing_type=sa.VARCHAR(),
        type_=sa.Text(),
        nullable=True,
    )
    op.alter_column(
        "bank_statement",
        "client_name",
        existing_type=sa.VARCHAR(),
        type_=sa.Text(),
        nullable=True,
    )
    op.alter_column(
        "bank_statement",
        "transaction",
        existing_type=sa.VARCHAR(),
        type_=sa.Text(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "bank_statement",
        "transaction",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "bank_statement",
        "client_name",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "bank_statement",
        "period",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "bank_statement",
        "main_currency",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "bank_statement",
        "branch_of_the_bank",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "bank_statement",
        "card",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "bank_statement",
        "account_number",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "bank_statement",
        "contract_number",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(),
        nullable=False,
    )
    # ### end Alembic commands ###
